#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentProperty.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="propertyDB")]
	public partial class LandLordClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public LandLordClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["propertyDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LandLordClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LandLordClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LandLordClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LandLordClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spRegister")]
		public int spRegister([global::System.Data.Linq.Mapping.ParameterAttribute(Name="FullName", DbType="VarChar(200)")] string fullName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(100)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="VarChar(100)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MobileNumber", DbType="BigInt")] System.Nullable<long> mobileNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Place", DbType="VarChar(100)")] string place, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProfileImage", DbType="VarChar(255)")] string profileImage)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fullName, email, password, mobileNumber, place, profileImage);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[_propertyinfo]")]
		public int _propertyinfo([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PropertyImage", DbType="VarChar(200)")] string propertyImage, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PropertyName", DbType="VarChar(200)")] string propertyName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SquareFts", DbType="Int")] System.Nullable<int> squareFts, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RentCost", DbType="Int")] System.Nullable<int> rentCost, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="City", DbType="VarChar(50)")] string city, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Location", DbType="VarChar(200)")] string location, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Type", DbType="Float")] System.Nullable<double> type, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LandLordName", DbType="VarChar(200)")] string landLordName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LandLordImage", DbType="VarChar(200)")] string landLordImage, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserId", DbType="Int")] System.Nullable<int> userId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), propertyImage, propertyName, squareFts, rentCost, city, location, type, landLordName, landLordImage, userId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[_deleteProperty]")]
		public int _deleteProperty([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PropertyId", DbType="Int")] System.Nullable<int> propertyId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), propertyId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[_updateProperty]")]
		public int _updateProperty([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PropertyId", DbType="Int")] System.Nullable<int> propertyId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PropertyImage", DbType="VarChar(200)")] string propertyImage, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PropertyName", DbType="VarChar(200)")] string propertyName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SquareFts", DbType="Int")] System.Nullable<int> squareFts, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RentCost", DbType="Int")] System.Nullable<int> rentCost, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="City", DbType="VarChar(50)")] string city, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Location", DbType="VarChar(200)")] string location, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Type", DbType="Float")] System.Nullable<double> type, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LandLordName", DbType="VarChar(200)")] string landLordName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] ref System.Nullable<long> output)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), propertyId, propertyImage, propertyName, squareFts, rentCost, city, location, type, landLordName, output);
			output = ((System.Nullable<long>)(result.GetParameterValue(9)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[_getOtherUserProperty]")]
		public ISingleResult<_getOtherUserPropertyResult> _getOtherUserProperty([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserId", DbType="Int")] System.Nullable<int> userId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userId);
			return ((ISingleResult<_getOtherUserPropertyResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spLogIn")]
		public ISingleResult<spLogInResult> spLogIn([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(100)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="VarChar(100)")] string password)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), email, password);
			return ((ISingleResult<spLogInResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[_getPropertybyid]")]
		public ISingleResult<_getPropertybyidResult> _getPropertybyid([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PropertyId", DbType="Int")] System.Nullable<int> propertyId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), propertyId);
			return ((ISingleResult<_getPropertybyidResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[_requestSp]")]
		public int _requestSp([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PropertyId", DbType="Int")] System.Nullable<int> propertyId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserId", DbType="Int")] System.Nullable<int> userId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), propertyId, userId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[_spGetRequest]")]
		public ISingleResult<_spGetRequestResult> _spGetRequest([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PropertyId", DbType="Int")] System.Nullable<int> propertyId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), propertyId);
			return ((ISingleResult<_spGetRequestResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[_getallProperty]")]
		public ISingleResult<_getallPropertyResult> _getallProperty([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserId", DbType="Int")] System.Nullable<int> userId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userId);
			return ((ISingleResult<_getallPropertyResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[_deleteRequest]")]
		public int _deleteRequest([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RequestId", DbType="Int")] System.Nullable<int> requestId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), requestId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[_spgetallrequest]")]
		public ISingleResult<_spgetallrequestResult> _spgetallrequest()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<_spgetallrequestResult>)(result.ReturnValue));
		}
	}
	
	public partial class _getOtherUserPropertyResult
	{
		
		private int _PropertyId;
		
		private string _PropertyImage;
		
		private string _PropertyName;
		
		private int _SquareFts;
		
		private int _RentCost;
		
		private string _City;
		
		private string _Location;
		
		private double _Type;
		
		private string _LandLordName;
		
		private string _LandLordImage;
		
		private int _UserId;
		
		public _getOtherUserPropertyResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PropertyId", DbType="Int NOT NULL")]
		public int PropertyId
		{
			get
			{
				return this._PropertyId;
			}
			set
			{
				if ((this._PropertyId != value))
				{
					this._PropertyId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PropertyImage", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string PropertyImage
		{
			get
			{
				return this._PropertyImage;
			}
			set
			{
				if ((this._PropertyImage != value))
				{
					this._PropertyImage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PropertyName", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string PropertyName
		{
			get
			{
				return this._PropertyName;
			}
			set
			{
				if ((this._PropertyName != value))
				{
					this._PropertyName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SquareFts", DbType="Int NOT NULL")]
		public int SquareFts
		{
			get
			{
				return this._SquareFts;
			}
			set
			{
				if ((this._SquareFts != value))
				{
					this._SquareFts = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RentCost", DbType="Int NOT NULL")]
		public int RentCost
		{
			get
			{
				return this._RentCost;
			}
			set
			{
				if ((this._RentCost != value))
				{
					this._RentCost = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this._City = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Location
		{
			get
			{
				return this._Location;
			}
			set
			{
				if ((this._Location != value))
				{
					this._Location = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="Float NOT NULL")]
		public double Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this._Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LandLordName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string LandLordName
		{
			get
			{
				return this._LandLordName;
			}
			set
			{
				if ((this._LandLordName != value))
				{
					this._LandLordName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LandLordImage", DbType="VarChar(200)")]
		public string LandLordImage
		{
			get
			{
				return this._LandLordImage;
			}
			set
			{
				if ((this._LandLordImage != value))
				{
					this._LandLordImage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Int NOT NULL")]
		public int UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this._UserId = value;
				}
			}
		}
	}
	
	public partial class spLogInResult
	{
		
		private string _FullName;
		
		private string _Email;
		
		private string _Password;
		
		private int _UserId;
		
		public spLogInResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string FullName
		{
			get
			{
				return this._FullName;
			}
			set
			{
				if ((this._FullName != value))
				{
					this._FullName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Int NOT NULL")]
		public int UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this._UserId = value;
				}
			}
		}
	}
	
	public partial class _getPropertybyidResult
	{
		
		private int _PropertyId;
		
		private string _PropertyImage;
		
		private string _PropertyName;
		
		private int _SquareFts;
		
		private int _RentCost;
		
		private string _City;
		
		private string _Location;
		
		private double _Type;
		
		private string _LandLordName;
		
		private string _LandLordImage;
		
		private int _UserId;
		
		public _getPropertybyidResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PropertyId", DbType="Int NOT NULL")]
		public int PropertyId
		{
			get
			{
				return this._PropertyId;
			}
			set
			{
				if ((this._PropertyId != value))
				{
					this._PropertyId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PropertyImage", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string PropertyImage
		{
			get
			{
				return this._PropertyImage;
			}
			set
			{
				if ((this._PropertyImage != value))
				{
					this._PropertyImage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PropertyName", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string PropertyName
		{
			get
			{
				return this._PropertyName;
			}
			set
			{
				if ((this._PropertyName != value))
				{
					this._PropertyName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SquareFts", DbType="Int NOT NULL")]
		public int SquareFts
		{
			get
			{
				return this._SquareFts;
			}
			set
			{
				if ((this._SquareFts != value))
				{
					this._SquareFts = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RentCost", DbType="Int NOT NULL")]
		public int RentCost
		{
			get
			{
				return this._RentCost;
			}
			set
			{
				if ((this._RentCost != value))
				{
					this._RentCost = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this._City = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Location
		{
			get
			{
				return this._Location;
			}
			set
			{
				if ((this._Location != value))
				{
					this._Location = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="Float NOT NULL")]
		public double Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this._Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LandLordName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string LandLordName
		{
			get
			{
				return this._LandLordName;
			}
			set
			{
				if ((this._LandLordName != value))
				{
					this._LandLordName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LandLordImage", DbType="VarChar(200)")]
		public string LandLordImage
		{
			get
			{
				return this._LandLordImage;
			}
			set
			{
				if ((this._LandLordImage != value))
				{
					this._LandLordImage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Int NOT NULL")]
		public int UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this._UserId = value;
				}
			}
		}
	}
	
	public partial class _spGetRequestResult
	{
		
		private string _FullName;
		
		private string _Email;
		
		private System.Nullable<long> _MobileNumber;
		
		private string _place;
		
		public _spGetRequestResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string FullName
		{
			get
			{
				return this._FullName;
			}
			set
			{
				if ((this._FullName != value))
				{
					this._FullName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobileNumber", DbType="BigInt")]
		public System.Nullable<long> MobileNumber
		{
			get
			{
				return this._MobileNumber;
			}
			set
			{
				if ((this._MobileNumber != value))
				{
					this._MobileNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_place", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string place
		{
			get
			{
				return this._place;
			}
			set
			{
				if ((this._place != value))
				{
					this._place = value;
				}
			}
		}
	}
	
	public partial class _getallPropertyResult
	{
		
		private int _PropertyId;
		
		private string _PropertyImage;
		
		private string _PropertyName;
		
		private int _SquareFts;
		
		private int _RentCost;
		
		private string _City;
		
		private string _Location;
		
		private double _Type;
		
		private string _LandLordName;
		
		private string _LandLordImage;
		
		private int _UserId;
		
		public _getallPropertyResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PropertyId", DbType="Int NOT NULL")]
		public int PropertyId
		{
			get
			{
				return this._PropertyId;
			}
			set
			{
				if ((this._PropertyId != value))
				{
					this._PropertyId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PropertyImage", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string PropertyImage
		{
			get
			{
				return this._PropertyImage;
			}
			set
			{
				if ((this._PropertyImage != value))
				{
					this._PropertyImage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PropertyName", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string PropertyName
		{
			get
			{
				return this._PropertyName;
			}
			set
			{
				if ((this._PropertyName != value))
				{
					this._PropertyName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SquareFts", DbType="Int NOT NULL")]
		public int SquareFts
		{
			get
			{
				return this._SquareFts;
			}
			set
			{
				if ((this._SquareFts != value))
				{
					this._SquareFts = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RentCost", DbType="Int NOT NULL")]
		public int RentCost
		{
			get
			{
				return this._RentCost;
			}
			set
			{
				if ((this._RentCost != value))
				{
					this._RentCost = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this._City = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Location
		{
			get
			{
				return this._Location;
			}
			set
			{
				if ((this._Location != value))
				{
					this._Location = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="Float NOT NULL")]
		public double Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this._Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LandLordName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string LandLordName
		{
			get
			{
				return this._LandLordName;
			}
			set
			{
				if ((this._LandLordName != value))
				{
					this._LandLordName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LandLordImage", DbType="VarChar(200)")]
		public string LandLordImage
		{
			get
			{
				return this._LandLordImage;
			}
			set
			{
				if ((this._LandLordImage != value))
				{
					this._LandLordImage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Int NOT NULL")]
		public int UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this._UserId = value;
				}
			}
		}
	}
	
	public partial class _spgetallrequestResult
	{
		
		private int _RequestId;
		
		private int _UserId;
		
		private int _PropertyId;
		
		public _spgetallrequestResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequestId", DbType="Int NOT NULL")]
		public int RequestId
		{
			get
			{
				return this._RequestId;
			}
			set
			{
				if ((this._RequestId != value))
				{
					this._RequestId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Int NOT NULL")]
		public int UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this._UserId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PropertyId", DbType="Int NOT NULL")]
		public int PropertyId
		{
			get
			{
				return this._PropertyId;
			}
			set
			{
				if ((this._PropertyId != value))
				{
					this._PropertyId = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
